name: build

on:
  push:
    branches:
      - "*.*.x"
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        run: |
          echo "$GITHUB_REF_NAME will serve the internal behavior of GitHub Action"
          echo "${{ env.GITHUB_REF_NAME }} will serve the behavior of the GitHub Slug action"
        shell: bash
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          target: base
          tags: teltek/pumukit-base:latest